function nameConversionTable = xASL_adm_GetDeprecatedFields()
%xASL_adm_GetDeprecatedFields Get the names of all deprecated fields and
%their corresponding new field names
%
% FORMAT: nameConversionTable = xASL_adm_GetDeprecatedFields()
%
% INPUT:
%   n/a
%
% OUTPUT:
%   nameConversionTable - Conversion table
%
% -----------------------------------------------------------------------------------------------------------------------------------------------------
% DESCRIPTION: This script is mainly used to improve backwards
%              compatibility. Check the usage in both xASL_adm_LoadX 
%              and xASL_io_ReadDataPar.
%
% EXAMPLE:     n/a
%
% __________________________________
% Copyright (C) 2015-2021 ExploreASL


nameConversionTable = {...
    'nSessions'                     'dataset'       'nSessions'                     '';...
    'nSubjectsSessions'             'dataset'       'nSubjectsSessions'             '';...
    'nTotalSubjects'                'dataset'       'nTotalSubjects'                '';...
    'TotalSubjects'                 'dataset'       'TotalSubjects'                 '';...
    'nTimePoints'                   'dataset'       'nTimePoints'                   '';...
    'exclusion'                     'dataset'       'exclusion'                     '';...
    'TimePointSubjects'             'dataset'       'TimePointSubjects'             '';...
    'nTimePointSubjects'            'dataset'       'nTimePointSubjects'            '';...
    'ExcludedSubjects'              'dataset'       'ExcludedSubjects'              '';...
    'nTimePointExcluded'            'dataset'       'nTimePointExcluded'            '';...
    'TimePointTotalSubjects'        'dataset'       'TimePointTotalSubjects'        '';...
    'TimePointExcluded'             'dataset'       'TimePointExcluded'             '';...
    'nTimePointTotalSubjects'       'dataset'       'nTimePointTotalSubjects'       '';...
    'nTimePointsTotal'              'dataset'       'nTimePointsTotal'              '';...
    'nExcluded'                     'dataset'       'nExcluded'                     '';...
    'TotalInclusionList'            'dataset'       'TotalInclusionList'            '';...
    'SpaghettiDir'                  'D'             'SpaghettiDir'                  '';...
    'HistogramDir'                  'D'             'HistogramDir'                  '';...
    'StatsMaps'                     'D'             'StatsMaps'                     '';...
    'SPMDIR'                        'D'             'SPMDIR'                        '';...
    'SPMpath'                       'D'             'SPMpath'                       '';...
    'LockDir'                       'dir'           'LockDir'                       '';...
    'dataParType'                   'opts'          'dataParType'                   '';...
    'SPMVERSION'                    'tools'         'SPMVERSION'                    '';...
    'BILAT_FILTER'                  'settings'      'BILAT_FILTER'                  '';...
    'Pediatric_Template'            'settings'      'Pediatric_Template'            '';...
    'bReproTesting'                 'settings'      'bReproTesting'                 '';...
    'bOverwrite'                    'settings'      'bOverwrite'                    '';...
    'dryRun'                        'settings'      'dryRun'                        '';...
    'M0_conventionalProcessing'     'settings'      'M0_conventionalProcessing'     '';...
    'SegmentSPM12'                  'settings'      'SegmentSPM12'                  '';...
    'bAutoACPC'                     'settings'      'bAutoACPC'                     '';...
    'RERUN'                         'settings'      'RERUN'                         '';...
    'MUTEXID'                       'settings'      'MUTEXID'                       '';...
    'bLesionFilling'                'settings'      'bLesionFilling'                '';...
    'stopAfterErrors'               'settings'      'stopAfterErrors'               ''
    };

end




