function UnitTest = xASL_ut_function_xASL_bids_Config(TestRepository)
%xASL_ut_function_xASL_bids_Config Individual unit test for xASL_bids_Config
%
% INPUT:        TestRepository - Path to test repository.
%
% OUTPUT:       UnitTest  - Test structure
%               name      - Name of tested module or submodule (char array)
%               unit      - Insert one of the following: 'Module', 'Submodule' or 'Function'
%               passed    - Result of all subtests combined (true or false)
%               test      - Structure with individual subtest results
%
% -----------------------------------------------------------------------------------------------------------------------------------------------------
% DESCRIPTION:  Should be run using xASL_ut_UnitTesting.
%
% EXAMPLE:      UnitTests(1) = xASL_ut_function_xASL_bids_Config(TestRepository);
% -----------------------------------------------------------------------------------------------------------------------------------------------------
% Copyright 2015-2021 ExploreASL


%% Test run 1

% Give your individual subtest a name
UnitTest.tests(1).testname = 'Create default bidsPar struct';

% Start the test
testTime = tic;

% Run your test here
bidsPar = xASL_bids_Config();

% Define one or multiple test conditions here
testCondition = true;

% Define one or multiple test conditions here
if ~isstruct(bidsPar)
    testCondition = false;
end
% Check if all fields exist
if ~isfield(bidsPar,'BIDSVersion') || ...
   ~isfield(bidsPar,'listFieldsRemoveGeneral') || ...
   ~isfield(bidsPar,'listFieldsRemoveASL') || ...
   ~isfield(bidsPar,'listFieldsRemoveM0') || ...
   ~isfield(bidsPar,'listFieldsRemoveNonASL') || ...
   ~isfield(bidsPar,'listFieldOrder') || ...
   ~isfield(bidsPar,'ASLfields') || ...
   ~isfield(bidsPar,'M0fields') || ...
   ~isfield(bidsPar,'stringAslContext') || ...
   ~isfield(bidsPar,'stringLabel') || ...
   ~isfield(bidsPar,'stringControl') || ...
   ~isfield(bidsPar,'stringM0scan') || ...
   ~isfield(bidsPar,'stringCbf') || ...
   ~isfield(bidsPar,'stringDeltaM') || ...
   ~isfield(bidsPar,'stringM0Separate') || ...
   ~isfield(bidsPar,'stringM0Included') || ...
   ~isfield(bidsPar,'stringM0Estimate') || ...
   ~isfield(bidsPar,'stringM0Absent') || ...
   ~isfield(bidsPar,'stringPerfusion') || ...
   ~isfield(bidsPar,'stringFmap') || ...
   ~isfield(bidsPar,'sidecarName') || ...
   ~isfield(bidsPar,'sidecarRequired') || ...
   ~isfield(bidsPar,'sidecarTypeSpecific') || ...
   ~isfield(bidsPar,'sidecarSuffixType') || ...
   ~isfield(bidsPar,'ASLCondition') || ...
   ~isfield(bidsPar,'listRemoveIfEmpty') || ...
   ~isfield(bidsPar,'listAnatTypes') || ...
   ~isfield(bidsPar,'BIDS2LegacyFolderConfiguration') || ...
   ~isfield(bidsPar,'datasetDescription')
    testCondition = false;
end

% Get test duration
UnitTest.tests(1).duration = toc(testTime);

% Evaluate your test
UnitTest.tests(1).passed = testCondition;


%% End of testing
UnitTest = xASL_ut_CheckSubtests(UnitTest);

end


